apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmined
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: local-storage
  volumeName: unmined
