apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria-session
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
