apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: vanadis
spec:
  hosts:
    - role: controller+worker
      noTaints: true
      privateInterface: eno3
      openSSH:
        address: ns3066513.ip-79-137-70.eu
        user: debian
    - role: controller+worker
      noTaints: true
      privateInterface: eno3
      openSSH:
        address: ns3066688.ip-79-137-70.eu
        user: debian
    - role: controller+worker
      noTaints: true
      privateInterface: eno1
      openSSH:
        address: ns3138770.ip-94-23-11.eu
        user: debian
    - role: worker
      privateInterface: eth0
      openSSH:
        address: 95-111-216-67.au-syd1.upcloud.host
        user: root
  k0s:
    version: v1.30.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: vanadis
      spec:
        api:
          extraArgs:
            service-node-port-range: 53-32767
        network:
          provider: calico
          calico:
            mtu: 0
