apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  groups:
    - snapshot
  task: snapshot
  cron: "0 * * * *"
  retain: 23
  concurrency: 2
