apiVersion: v1
kind: Node
metadata:
  name: ns3066513
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    storage: "true"
    topology.kubernetes.io/region: eu-central-waw
    topology.kubernetes.io/zone: eu-central-waw-a
  annotations:
    node.longhorn.io/default-node-tags: '["ns3066513"]'
