apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: jellyfin
