apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcodes
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
