apiVersion: apps/v1
kind: Deployment
metadata:
  name: lftp
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lftp
  template:
    metadata:
      labels:
        app: lftp
      annotations:
        kubectl.kubernetes.io/default-container: lftp
    spec:
      initContainers:
        - name: bootstrap
          image: busybox
          command:
            - ln
            - -sf
            - /proc/self/fd/1
            - /root/.local/share/lftp/transfer_log
          volumeMounts:
            - name: lftp-data
              mountPath: /root/.local/share/lftp
      containers:
        - name: lftp
          image: minidocks/lftp # Docker image with lftp installed
          command:
            - lftp
          stdin: true
          tty: true
          workingDir: /anime
          volumeMounts:
            - name: anime
              mountPath: /anime
            - name: lftprc
              mountPath: /root/.lftprc
              subPath: .lftprc
            - name: lftp-data
              mountPath: /root/.local/share/lftp
      volumes:
        - name: anime
          persistentVolumeClaim:
            claimName: anime
        - name: lftprc
          configMap:
            name: lftprc
        - name: lftp-data
          persistentVolumeClaim:
            claimName: lftp-data
