apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-storage
  volumeName: pvc-default-minecraft-world
