apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-csi-pvc
  annotations:
    argocd.argoproj.io/sync-options: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: seaweedfs-storage
